--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin
-- this is a simple entity class that generates unique IDs for each entity
-- index means that if a key is not found in the table, it will look for it in the metatable
Entity = {}
Entity.__index = Entity
Entity.nextId = 0

-- entity id generator

function Entity:new(x, y)
    local e = setmetatable({}, Entity)

    -- unique ID (like C++ object ID)
    Entity.nextId = Entity.nextId + 1
    e.id = Entity.nextId

    -- core data (like class members in C++)
    e.x = x or 0
    e.y = y or 0

    e.vx = 0
    e.vy = 0

    e.alive = true

    return e
end

function Entity:update(dt)
    -- basic movement
    self.x = self.x + self.vx * dt
    self.y = self.y + self.vy * dt
end

function Entity:draw()
    -- override in child types
end

--function
--endregion
