--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin
-- this is a simple entity class that generates unique IDs for each entity
-- index means that if a key is not found in the table, it will look for it in the metatable
Entity = {}
Entity.__index = Entity
Entity.nextId = 0

Entity.states = { }  -- possible states for entities

Entity.states.idle = function(self, dt)
    self.vx = 0
    self.vy = 0
end

Entity.states.move = function(self, dt)
    -- example move state
    self.vx = 50
end

-- entity id generator

function Entity:new(x, y)
    local e = setmetatable({}, Entity)

    -- unique ID (like C++ object ID)
    Entity.nextId = Entity.nextId + 1
    e.id = Entity.nextId

    -- core data (like class members in C++)
    e.x = x or 0
    e.y = y or 0

    e.vx = 0
    e.vy = 0

    e.alive = true

    e.state = "idle" -- default state

    return e
end

function Entity:update(dt)

    -- run behaviour based on state
    local stateFunc = Entity.states[self.state]
    if stateFunc then
        stateFunc(self, dt)
    end

    -- basic movement
    self.x = self.x + self.vx * dt
    self.y = self.y + self.vy * dt

-- override in child types

end

function Entity:draw()
    -- override in child types
end

--function
--endregion
