--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin

function integrate(p)
    p.velx += p.fx / p.mass
    p.vely += p.fy / p.mass

    p.fx = 0
    p.fy = 0
end


function move_y(p)
    local ny = p.y + p.vely

    if collide_map(p.x, ny, p.w, p.h) then
        if p.vely > 0 then
            p.y = flr((ny + p.h) / 8) * 8 - p.h
            p.state = "grounded"
        elseif p.vely < 0 then
            p.y = flr(ny / 8 + 1) * 8
        end
        p.vely = 0
    else
        p.y = ny
        p.state = "airborne"
    end
end

function move_x(p)
    local nx = p.x + p.velx

    if collide_map(nx, p.y, p.w, p.h) then
        if p.velx > 0 then
            p.x = flr((nx + p.w) / 8) * 8 - p.w
        elseif p.velx < 0 then
            p.x = flr(nx / 8 + 1) * 8
        end
        p.velx = 0
    else
        p.x = nx
    end
end

function updatePhysics()
    local p = player

    -- forces
    p.fy += 0.6 -- gravity

    -- integrate velocity
    integrate(p)

    -- collision resolution
    move_x(p)
    move_y(p)
end
--endregion
