--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin

function integrate(p)

    local ax = p.fx / p.mass
    
    local ay = p.fy / p.mass
    
    p.vx += ax
    
    p.vy += ay
    
    p.vx *= 0.85
    
    p.x += p.vx
    
    p.y += p.vy
    
    p.fx = 0
    p.fy = 0
end

function collisionCheck(p1, p2)
    local dx = p2.x - p1.x
    local dy = p2.y - p1.y
    local dist = math.sqrt(dx * dx + dy * dy)
    local minDist = p1.radius + p2.radius

    if dist < minDist then

        local angle = math.atan2(dy, dx)
        local targetX = p1.x + math.cos(angle) * minDist
        local targetY = p1.y + math.sin(angle) * minDist
        local ax = (targetX - p2.x) * 0.5
        local ay = (targetY - p2.y) * 0.5

        p1.vx -= ax / p1.mass
        p1.vy -= ay / p1.mass
        p2.vx += ax / p2.mass
        p2.vy += ay / p2.mass
    end
end

function resolveCollision() 

-- falling
    if p.vy > 0 then
      p.y = flr((ny + p.h) / 8) * 8 - p.h
      p.state = "grounded"
    -- jumping up
    elseif p.vy < 0 then
      p.y = flr(ny / 8 + 1) * 8
    end
    p.vy = 0
  else
    p.y = ny
    p.state = "airborne"
  end

end

function updatePhysics()

local p = player

if(collision_map(p.x, p.y, p.w, p.h)) then
    resolveCollision()
end

collisionCheck(p, 
integrate(p)

end
--endregion
