--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin

function solid(tx, ty)
  return fget(mget(tx, ty), 0)
end

function runSprites()

    local p = player
    local tx = flr(p.x / 8)
    local ty = flr(p.y / 8)
    
    local tile = mget(tx, ty)

    

     if fget(tile, 1) then
     p.state = "dead"

    end
end

function collide_map(x, y, w, h)
  local left   = flr(x / 8)
  local right  = flr((x + w - 1) / 8)
  local top    = flr(y / 8)
  local bottom = flr((y + h - 1) / 8)

  for tx = left, right do
    for ty = top, bottom do
      if solid(tx, ty) then
        return true
      end
    end
  end

  return false
end
--endregion
