--region *.lua
--Date
--This file is automatically generated by the 【BabeLua】 plugin

#include "Forces.lua"

function solid(tx, ty)
  return fget(mget(tx, ty), 0)
end

function runSprites()

    local p = player
    tx = flr(x / 8)
    ty = flr(y / 8)
    
    tile = mget(tx, ty)

    

    if(collide_map(p.x, p.y, p.w, p.h)) then
     
    end
end

function collide_map(x, y, w, h)
  local left   = flr(x / 8)
  local right  = flr((x + w - 1) / 8)
  local top    = flr(y / 8)
  local bottom = flr((y + h - 1) / 8)

  for tx = left, right do
    for ty = top, bottom do
      if solid(tx, ty) then
        return true
      end
    end
  end

  return false
end
--endregion
